numOfAgents = 5000
seed = 3
maps = san-fran
regions = region_census.shp
initPercentInfectious = 0.1
selfQuarantinedProbability = 0
additionalDiseaseSpreadingParam = 0.05
numTikDelay = 0
knownCaseImpactParam = 0
maskWearingThreshold = 1
avgMaskEffectivity = 0.95
exposedLasting=3-14
infectiousLasting=5-8
recoveredLasting=14-180
stayingHome=1-4